name: weather_app_ca
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  # Flutter core
  flutter:
    sdk: flutter

  # UI components
  cupertino_icons: ^1.0.2
  iconly: ^1.0.1
  gap: ^3.0.1

  # State management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  provider: ^6.0.5
  get_it: ^7.6.4

  # Functional programming
  equatable: ^2.0.5
  dartz: ^0.10.1

  # File handling
  file_picker: ^5.5.0
  image_picker: ^1.0.4
  open_file: ^3.3.2
  path_provider: ^2.1.1

  # Internationalization
  intl: ^0.18.1

  # HTTP requests
  http: 
  geolocator: ^10.1.0
  google_maps_flutter: ^2.5.0
  search_map_place_updated: ^0.0.4
  flutter_google_places_hoc081098: ^1.2.0
  flutter_dotenv: ^5.1.0

dev_dependencies:
  # Flutter testing
  flutter_test:
    sdk: flutter

  # Linting and analysis
  flutter_lints: ^2.0.0
  very_good_analysis: ^5.1.0

  # Testing utilities
  bloc_test: ^9.1.4
  mocktail: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Aeonik
      fonts:
        - asset: assets/fonts/aeonik/AeonikTRIAL-Bold.otf
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-BoldItalic.otf
          style: italic
          weight: 700
        - asset: assets/fonts/aeonik/AeonikTRIAL-Light.otf
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-LightItalic.otf
          style: italic
          weight: 300
        - asset: assets/fonts/aeonik/AeonikTRIAL-Regular.otf
          weight: 400
        - asset: assets/fonts/aeonik/AeonikTRIAL-RegularItalic.otf
          style: italic
          weight: 400
